<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[screenshot taken]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="14978" started-at="2018-02-03T12:22:05Z" finished-at="2018-02-03T12:22:20Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="14978" started-at="2018-02-03T12:22:05Z" finished-at="2018-02-03T12:22:20Z">
      <class name="script.TestLoginPage">
        <test-method status="PASS" signature="setExtent()[pri:0, instance:script.TestLoginPage@101b7af]" name="setExtent" is-config="true" duration-ms="535" started-at="2018-02-03T17:52:05Z" finished-at="2018-02-03T17:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method status="PASS" signature="precondition()[pri:0, instance:script.TestLoginPage@101b7af]" name="precondition" is-config="true" duration-ms="10798" started-at="2018-02-03T17:52:06Z" finished-at="2018-02-03T17:52:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="testlogin()[pri:0, instance:script.TestLoginPage@101b7af]" name="testlogin" duration-ms="2395" started-at="2018-02-03T17:52:16Z" finished-at="2018-02-03T17:52:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [tested] but found [actiTIME - Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [tested] but found [actiTIME - Login]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at script.TestLoginPage.testlogin(TestLoginPage.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testlogin -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:script.TestLoginPage@101b7af]" name="getResult" is-config="true" duration-ms="674" started-at="2018-02-03T17:52:19Z" finished-at="2018-02-03T17:52:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testlogin status=FAILURE method=TestLoginPage.testlogin()[pri:0, instance:script.TestLoginPage@101b7af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[screenshot taken]]>
            </line>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="testDown()[pri:0, instance:script.TestLoginPage@101b7af]" name="testDown" is-config="true" duration-ms="539" started-at="2018-02-03T17:52:19Z" finished-at="2018-02-03T17:52:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDown -->
      </class> <!-- script.TestLoginPage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
